language: python

sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - sshpass

script:
  - sudo docker-compose up -d --build

after_success:
  - export SSHPASS=$DEPLOY_PASS
  - sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST ./deploy.sh

branches:
  only:
    - master
