language: python

sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - sshpass

script:
  - sudo docker-compose up -d --build

after_success:
  - sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh
