version: '3'

services:
  django:
    container_name: django
    build: .
    command: sleep 10
    command: /runserver.sh
    working_dir: /goldpenny
    ports:
      - 80:80
    depends_on:
      - postgres
    volumes:
      - ./goldpenny:/goldpenny
    env_file:
      - ./.envs/.django
      - ./.envs/.postgres
  
  postgres:
    image: postgres
    env_file:
      - ./.envs/.postgres
    ports:
<<<<<<< HEAD
      - "5433:5433"
=======
      - "5432:5432"
>>>>>>> c20651c4de68c8d3b27a271f2a15055cd542eb90
