# Generated by Django 2.0.5 on 2018-05-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180503_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_sold',
            field=models.BigIntegerField(default=0, verbose_name='Total Sold'),
        ),
        migrations.AlterField(
            model_name='event',
            name='total_earnings',
            field=models.FloatField(default=0, verbose_name='Total Earnings'),
        ),
    ]
