# Generated by Django 2.0.5 on 2018-05-02 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='product_list',
        ),
        migrations.AddField(
            model_name='product',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='event.Event'),
            preserve_default=False,
        ),
    ]
